import elementary_questions_algebraic_geometry_foundation_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace elementary_questions_algebraic_geometry_foundation_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end elementary_questions_algebraic_geometry_foundation_canonical_lane_mathlib
end HautevilleHouse
